version: '3.8'
services:
  flask:
    build: ./flask
    ports:
      - "5000"
  mongodb_service:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./data/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  haproxy:
    build: ./haproxy
    ports:
      - 80:80
    depends_on:
      - flask